//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public partial class asm_getLocationdata1_Result1
    {
        public int Location_Code { get; set; }
        public string Location_Name { get; set; }
        public int Parent_ID { get; set; }
        public string CreatedOn { get; set; }
        public string ModifiedOn { get; set; }
        public string Actions { get; set; }
    }
}
