//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.AssetDisposals = new HashSet<AssetDisposal>();
            this.Movements = new HashSet<Movement>();
        }
    
        public int ID { get; set; }
        public int Location_Code { get; set; }
        public int Category_Code { get; set; }
        public int Purchase_ID { get; set; }
        public string Asset_Number { get; set; }
        public string RFID_Tag { get; set; }
        public Nullable<int> Barcode { get; set; }
        public System.DateTime Created_On { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<System.DateTime> Deleted_On { get; set; }
        public bool IsDeleted { get; set; }
        public int BranchID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Location Location { get; set; }
        public virtual Purchase Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetDisposal> AssetDisposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movement> Movements { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
