//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisposalDetail
    {
        public int ID { get; set; }
        public int Disposal_ID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int CreatedBy { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
    
        public virtual Disposal Disposal { get; set; }
    }
}
