//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int ID { get; set; }
        public int Asset_ID { get; set; }
        public int Previous_Location { get; set; }
        public int New_Location { get; set; }
        public System.DateTime Movement_On { get; set; }
        public int Movement_By { get; set; }
        public int Movement_From { get; set; }
        public int Movement_To { get; set; }
        public string Movement_Reason { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
